### ISSUE TITLE
Design the visual design for badges for the Festival

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/badges.mozillafestival.org#1]

**Comment by chloeatplay** [comment]
First patch ready.
http://www.flickr.com/photos/66772999@N05/sets/72157636544646726/
Will iterate and finalise by EOW. Have planned feedback call tomorrow 10:30 ET.

**Comment by threeqube** [comment]
The karaoke one. I die.

**Comment by chloeatplay** [comment]
PNGS link just in case / https://www.dropbox.com/sh/fdvg1ukicfzqwru/iNUxNrYMNE

**Comment by threeqube** [comment]
All mozfest badges loaded up on http://badger.openbadges.org/ thanks to @jadeforester

**Comment by iamjessklein** [comment]
Marking this as closed. :+1:
