### ISSUE TITLE
Design the claim page for badges.mozillafestival.org

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/badges.mozillafestival.org#2]

**Comment by iamjessklein** [comment]
This is the design we are going with:

![10275271994_79a5211501_b](https://f.cloud.github.com/assets/535012/1346059/7593ccf6-369a-11e3-8213-46f3736d8fea.jpg)

For documentation, this is another design that I did:

![10275362895_2bac2d7e32_b](https://f.cloud.github.com/assets/535012/1346072/99c515da-369a-11e3-9076-ec98cde4dd98.jpg)

**Comment by iamjessklein** [comment]
@andrewhayward - @megcolek would like the text that says "less yack more hack, indeed." to be replaced with "now claim  your badges"

**Comment by megcolek** [comment]
Totally fine with the catchy text. But just noting that there isn't anything on this page that references badges, other than part of the URL, and I think there needs to be. Maybe "Enter your badge claim code here" if it fits?

I think we need something (even if its' small) that mentions badges, so there is some connection.

Megan Cole
Marketing + Community Strategy Lead
Mozilla Foundation
http://openbadges.org
@openbadges | @megcolek
e: megan@mozillafoundation.org
c: 202-577-6575

**Comment by threeqube** [comment]
+1 on the need to mention badges and tie that in.

**Comment by threeqube** [comment]
Btw, love the designs!

**Comment by emgollie** [comment]
Discussed with @megcolek. Let's update copy this way:

HEADER
You've arrived at MozFest
Less yack more hack, indeed.

BOX
Enter your badge claim code here

BUTTON
Claim

**Comment by iamjessklein** [comment]
:+1:

**Comment by iamjessklein** [comment]
reassigning to @andrewhayward for tweaking.

**Comment by andrewhayward** [comment]
"Less yack more hack, indeed" makes very little sense. Why the arbitrary "indeed"?

**Comment by iamjessklein** [comment]
If it makes no sense, why not just "less yak, more hack."

**Comment by threeqube** [comment]
That's fine by me.

**Comment by emgollie** [comment]
@megcolek and I found an email where "indeed" was suggested, but it must have been a joke. My humor reader is down for the day :)

Updated:

HEADER
You've arrived at MozFest
Less yack, more hack!

BOX
Enter your badge claim code here

BUTTON
Claim

**Comment by andrewhayward** [comment]
"Less yack", or "less yak"? They mean two different things to me.

**Comment by emgollie** [comment]
Per http://mozillafestival.org/about, the MozFest style is "yack."

**Comment by andrewhayward** [comment]
Done. And live.
