### ISSUE TITLE
email claim bug

### ISSUE THREAD

**Issue by carlacasilli** [mozilla/badges.mozillafestival.org#6]
The email for claiming a MozFest badge is showing code where it should be showing the badge description:
![screen shot 2013-10-24 at 3 53 38 am](https://f.cloud.github.com/assets/1039302/1398429/2a5a9186-3ca1-11e3-9872-6ad47748e338.png)

**Comment by threeqube** [comment]
This is still an issue...

**Comment by threeqube** [comment]
This is fixed with https://github.com/mozilla/openbadges-badges/pull/33
