### ISSUE TITLE
change CTA on MozFest claim email

### ISSUE THREAD

**Issue by carlacasilli** [mozilla/badges.mozillafestival.org#7]
Change badge emails CTA (Make this badge mine! >>) go to http://badges.openbadges.org/claim instead of http://badges.openbadges.org/badges? It also needs to include some notice that you may have already done this.

![screen shot 2013-10-24 at 3 53 38 am](https://f.cloud.github.com/assets/1039302/1398439/6521d9a0-3ca1-11e3-8d9d-98ca11afe573.png)

**Comment by emgollie** [comment]
Discussed with @carlacasilli. cc @threeqube.

UPDATED BODY COPY:
Congratulations. You've earned an Open Badge that you can share with your networks. If you haven't already, send it to your Mozilla Backpack [hyperlink] and start spreading the word on the sites that matter to you!

##

Please note: we can remove "I want to send this badge..." in bold and follow the body copy with the badge image and title.

**Comment by carlacasilli** [comment]
:+1:

**Comment by carlacasilli** [comment]
@cmcavoy @christensenep @threeqube I don't think this change has been implemented yet.

**Comment by threeqube** [comment]
I verified that it has been implemented. We're :facepunch:

**Comment by iamjessklein** [comment]
so - good to close this?

**Comment by threeqube** [comment]
Yep.
